services:
  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    volumes:
      - ./data:/app/data
      - ./db:/app/db

  ollama:
    image: ollama/ollama
    volumes:
      - ~/.ollama/models:/root/.ollama

  # Database service - Under Development and not currently being used.
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=captains_log_user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=captains_log_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
