services:
  app:
    image: ghcr.io/d-vella/captains-log:latest
    ports:
      - "8501:8501"
    depends_on:
      - db:
        condition: service_healthy
    environment:
      - OLLAMA_PRIMARY=${OLLAMA_PRIMARY}
      - OLLAMA_PRIMARY_MODEL=${OLLAMA_PRIMARY_MODEL}
      - OLLAMA_FALLBACK=${OLLAMA_FALLBACK}
      - OLLAMA_FALLBACK_MODEL=${OLLAMA_FALLBACK_MODEL}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DATABASE_BACKEND=${DATABASE_BACKEND}
      - WHISPER_SERVER_URL=${WHISPER_SERVER_URL}
    volumes:
      - ./data:/app/data
      - ./db:/app/db
      - ./cert.pem:/app/cert.pem:ro
      - ./key.pem:/app/key.pem:ro
      - ./.env:/app/.env:ro

  # Database service - Under Development and not currently being used.
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
