"""initial schema

Revision ID: 51e07a79f1f0
Revises: 
Create Date: 2026-07-06 19:01:14.198824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e07a79f1f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_enrichment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_entry_id', sa.Integer(), nullable=False),
    sa.Column('formatted_md', sa.Text(), nullable=False),
    sa.Column('followup_qs', sa.Text(), nullable=False),
    sa.Column('weekly_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['log_entry_id'], ['log_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_entry_id', sa.Integer(), nullable=False),
    sa.Column('audio_filename', sa.String(length=255), nullable=False),
    sa.Column('audio_duration', sa.Integer(), nullable=False),
    sa.Column('raw_transcript', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['log_entry_id'], ['log_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_segment')
    op.drop_table('log_enrichment')
    op.drop_table('log_entry')
    # ### end Alembic commands ###
