"""initial schema

Revision ID: bd0bbe78a193
Revises: 
Create Date: 2026-04-18 08:29:19.303042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd0bbe78a193'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_enrichment', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('log_enrichment', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('log_enrichment', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('log_enrichment', 'formatted_md',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('log_enrichment', 'followup_qs',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('log_enrichment', 'weekly_summary',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('log_enrichment', 'generated_at')
    op.alter_column('log_entry', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('log_entry', 'entry_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=25),
               existing_nullable=False)
    op.add_column('log_segment', sa.Column('audio_duration', sa.Integer(), nullable=False))
    op.add_column('log_segment', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('log_segment', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('log_segment', 'audio_filename',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('log_segment', 'raw_transcript',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('log_segment', 'duration_secs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_segment', sa.Column('duration_secs', sa.REAL(), nullable=True))
    op.alter_column('log_segment', 'raw_transcript',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('log_segment', 'audio_filename',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('log_segment', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('log_segment', 'updated_at')
    op.drop_column('log_segment', 'audio_duration')
    op.alter_column('log_entry', 'entry_date',
               existing_type=sa.String(length=25),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('log_entry', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('log_enrichment', sa.Column('generated_at', sa.DATETIME(), nullable=False))
    op.alter_column('log_enrichment', 'weekly_summary',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('log_enrichment', 'followup_qs',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('log_enrichment', 'formatted_md',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('log_enrichment', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('log_enrichment', 'updated_at')
    op.drop_column('log_enrichment', 'created_at')
    # ### end Alembic commands ###
